BlogBundle\Entity\EntryTag:
    type: entity
    table: entry_tag
    indexes:
        pk_entry_tag_entries:
            columns:
                - entry_id
        pk_entry_tag_tags:
            columns:
                - tag_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        entry:
            targetEntity: Entry
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            #Indicar que va usar la entidad EntryTag
            #inversedBy: null
            inversedBy: entryTag
            joinColumns:
                entry_id:
                    referencedColumnName: id
            orphanRemoval: false
        tag:
            targetEntity: Tag
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            #Indicar que va usar la entidad EntryTag
            #inversedBy: null
            inversedBy: entryTag
            joinColumns:
                tag_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
